const Error = require('./Error');

/**
 * @func    Error.list
 * @param   {object} options
 * @returns {object}
 * @throws  {error}
 */
exports.list = async (options={}) => {
  const params = await ;
};

/**
 * @func    Error.describe
 * @param   {object} options
 * @returns {object}
 * @throws  {error}
 */
exports.describe = async (options={}) => {
  const params = await ;
};

/**
 * @func    Error.get
 * @param   {object} options
 * @returns {object}
 * @throws  {error}
 */
exports.get = async (options={}) => {
  const params = await ;
};

/**
 * @func    Error.create
 * @param   {object} options
 * @returns {object}
 * @throws  {error}
 */
exports.create = async (options={}) => {
  const params = await ;
};

/**
 * @func    Error.update
 * @param   {object} options
 * @returns {object}
 * @throws  {error}
 */
exports.update = async (options={}) => {
  const params = await ;
};

/**
 * @func    Error.delete
 * @param   {object} options
 * @returns {object}
 * @throws  {error}
 */
exports.delete = async (options={}) => {
  const params = await ;
};
